name: CapstoneEnv1
dependencies:
- openssl=1.0.2f=0
- pip=8.0.2=py27_0
- python=2.7.11=0
- pytz=2015.7=py27_0
- readline=6.2=2
- setuptools=19.6.2=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - kafka-python==1.0.1
  - six==1.10.0

